src/Entity/Album.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AlbumRepository")
 */
class Album
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $album_name;

    /**
     * @ORM\Column(type="date")
     */
    private $album_date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Photo", mappedBy="photo_album")
     */
    private $album_photos;

    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $password;

    /**
     * @ORM\Column(type="string")
     */
    private $category;

    public function __construct()
    {
        $this->album_photos = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param mixed $password
     */
    public function setPassword($password)
    {
        $this->password = $password;
    }

    /**
     * @return mixed
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param mixed $category
     */
    public function setCategory($category)
    {
        $this->category = $category;
    }




    public function getPhotos()
    {
        return $this->album_photos;
    }

    public function addPhoto(?Photo $photo): void
    {
        $photo->setPost($this);
        if (!$this->album_photos->contains($photo)) {
            $this->album_photos->add($photo);
        }
    }
    public function removePhoto(Photo $photo): void
    {
        $photo->setPost(null);
        $this->album_photos->removeElement($photo);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAlbumName(): ?string
    {
        return $this->album_name;
    }

    public function setAlbumName(string $album_name): self
    {
        $this->album_name = $album_name;

        return $this;
    }

    public function getAlbumDate(): ?\DateTimeInterface
    {
        return $this->album_date;
    }

    public function setAlbumDate(\DateTimeInterface $album_date): self
    {
        $this->album_date = $album_date;

        return $this;
    }
}

src/Entity/Photo.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PhotoRepository")
 */
class Photo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     *
     * @Assert\NotBlank(message="Veuillez choisir une photo à mettre en ligne")
     * @Assert\File(mimeTypes={ "image/png","image/jpeg" })
     */
    private $photo;

    /**
     * @ORM\Column(type="string")
     *
     * @Assert\File(mimeTypes={ "image/png","image/jpeg" })
     */
    private $watermark;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo_name;

    /**
     * @ORM\Column(type="date")
     */
    private $photo_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Album", inversedBy="album_photos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $photo_album;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Personne", mappedBy="photo", orphanRemoval=true)
     */
    private $personnes;

    public function __construct()
    {
        $this->personnes = new ArrayCollection();
    }

    public function getAlbum(): ?Album
    {
        return $this->photo_album;
    }

    public function setAlbum(?Album $album): self
    {
        $this->photo_album = $album;

        return $this;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getPhoto()
    {
        return $this->photo;
    }

    public function setPhoto($photo): self
    {
        $this->photo = $photo;
        return $this;
    }

    public function getWatermark()
    {
        return $this->watermark;
    }

    public function setWatermark($watermark): self
    {
        $this->watermark = $watermark;
        return $this;
    }

    public function getPhotoName(): ?string
    {
        return $this->photo_name;
    }

    public function setPhotoName(string $photo_name): self
    {
        $this->photo_name = $photo_name;

        return $this;
    }


    public function getPhotoDate(): ?\DateTimeInterface
    {
        return $this->photo_date;
    }

    public function setPhotoDate(\DateTimeInterface $photo_date): self
    {
        $this->photo_date = $photo_date;

        return $this;
    }

    /**
     * @return Collection|Personne[]
     */
    public function getPersonnes(): Collection
    {
        return $this->personnes;
    }

    public function addPersonne(Personne $personne): self
    {
        if (!$this->personnes->contains($personne)) {
            $this->personnes[] = $personne;
            $personne->setPhoto($this);
        }

        return $this;
    }

    public function removePersonne(Personne $personne): self
    {
        if ($this->personnes->contains($personne)) {
            $this->personnes->removeElement($personne);
            // set the owning side to null (unless already changed)
            if ($personne->getPhoto() === $this) {
                $personne->setPhoto(null);
            }
        }

        return $this;
    }
}

src/Controller/Gestion/GestionController.php
<?php

namespace App\Controller\Gestion;


use App\Entity\Achat;
use App\Entity\Album;
use App\Entity\Carousel;
use App\Entity\Client;
use App\Entity\Format;
use App\Entity\Personne;
use App\Entity\Photo;
use App\Entity\Presse;
use Sonata\CoreBundle\Form\Type\BooleanType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\PercentType;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class GestionController extends Controller
{

    /**
     * @Route("/gestion-site", name="gestion-site")
     */
    public function index() {
        return $this->redirectToRoute('gestion-site-albums');
    }

    /**
     * @Route("/gestion-site/album", name="gestion-site-albums")
     */
    public function albums(Request $request) {

        $albums = $this->getDoctrine()
            ->getRepository(Album::class)
            ->findAll();

        $album = new Album();
        $album->setAlbumDate(new \DateTime());

        $form = $this->createFormBuilder($album)
            ->add('albumName', TextType::class,
                array(
                    'label' => false,
                    'attr' => array(
                        'placeholder' => 'Nom de l\'album',
                        'class' => 'col l4 m4 s12 contactInput browser-default'
                    )
                ))
            ->add('category', ChoiceType::class,
                array(
                    'choices' => array(
                        'Album payant' => 'payant',
                        'Album gratuit' => 'free',
                        'Album payant protégé' => 'payant_protected',
                        'Album gratuit protégé' => 'free_protected',
                    ),
                    'label' => false,
                    'attr' => array(
                        'placeholder' => 'Nom de l\'album',
                        'class' => 'col l3 m3 offset-l1 offset-m1 s12 contactInput'
                    )
                ))
            ->add('add', SubmitType::class, array('label' => 'Ajouter l\'album','attr' => array('class' => 'col l3 m3 offset-l1 offset-m1 s12 buttonGerer noInputStyle button buttonGreen')))
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $album = $form->getData();
            if (strpos($album->getCategory(),'protected') !== false) {
                $album->setPassword(md5(uniqid()));
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($album);
            $entityManager->flush();
            $this->get('session')->getFlashBag()->add('success',"Album " . $album->getAlbumName() . " créé");
            return $this->redirectToRoute('gestion-site-albums');
        }

        return $this->render('gestion/album.html.twig',array(
            'form' => $form->createView(),
            'albums' => $albums,
            ''
        ));
    }


    /**
     * @Route("/gestion-site/prix", name="gestion-site-prix")
     */
    public function prix(Request $request) {

        $formats = $this->getDoctrine()
            ->getRepository(Format::class)
            ->findAll();

        $format = new Format();

        $form = $this->createFormBuilder($format)
            ->add('categorie', ChoiceType::class,
                array(
                    'label' => false,
                    'choices'  => array(
                        'Professionnel' => 'professionnel',
                        'Particulier' => 'particulier',
                    ),
                    'attr' => array(
                        'placeholder' => 'Categorie',
                        'class' => 'col l2 m2 s12 contactInput browser-default'
                    )
                ))
            ->add('ratioTaille', RangeType::class,
                array(
                    'label' => false,
                    'label_format' => false,
                    'attr' => array(
                        'step' => '0.01',
                        'max' => '1',
                        'min' => '0.01',
                        'placeholder' => 'Ratio de taille',
                        'oninput' => 'changeRatio(this)',
                        'class' => 'col l2 m2 s11 rangeInput contactInput browser-default'
                    )
                ))
            ->add('prix', IntegerType::class,
                array(
                    'label' => false,
                    'attr' => array(
                        'placeholder' => 'Prix',
                        'class' => 'col l2 m2 s12 offset-l1 offset-m1 contactInput browser-default'
                    )
                ))
            ->add('add', SubmitType::class, array('label' => 'Ajouter','attr' => array('class' => 'col l2 m2 s12  offset-l1 offset-m1  buttonGerer noInputStyle button buttonGreen')))
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ( $form->isValid()) {
                $format = $form->getData();
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($format);
                $entityManager->flush();
                $this->get('session')->getFlashBag()->add('success','Tarification ajoutée');
                return $this->redirectToRoute('gestion-site-prix');
            }else {
                $this->get('session')->getFlashBag()->add('error','Erreur de saisie');
            }
        }

        return $this->render('gestion/prix.html.twig',array(
            'form' => $form->createView(),
            'formats' => $formats
        ));
    }

    /**
     * @Route("/gestion-site/albums/{id}/ajouter-personne", name="ajouterPersonne")
     */
    public function ajouterPersonne(Photo $photo, Request $request) {

        $personnes = $this->getDoctrine()
            ->getRepository(Personne::class)
            ->findBy(array(
                'photo' => $photo
            ));

        $personne = new Personne();
        $personne->setPhoto($photo);

        $form = $this->createFormBuilder($personne)
            ->add('nom', TextType::class,
                array(
                    'label' => false,
                    'attr' => array(
                        'placeholder' => 'Nom',
                        'class' => 'col l3 m3 s12 contactInput browser-default'
                    )
                ))
            ->add('prenom', TextType::class,
                array(
                    'label' => false,
                    'attr' => array(
                        'placeholder' => 'Prenom',
                        'class' => 'col l3 m3 offset-l1 offset-m1 s12 contactInput browser-default'
                    )
                ))
            ->add('add', SubmitType::class, array('label' => 'Ajouter personne','attr' => array('class' => 'col l4 m4 offset-l1 offset-m1 s12 buttonGerer noInputStyle button buttonGreen')))
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $personne = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($personne);
            $entityManager->flush();
            $this->get('session')->getFlashBag()->add('success',$personne->getNom()." ". $personne->getPrenom() . " ajoutée");
            return $this->redirectToRoute('ajouterPersonne',array('id'=>$photo->getId()));
        }

        return $this->render('gestion/personnes.html.twig',array(
            'form' => $form->createView(),
            'personnes' => $personnes,
            'photo' => $photo
        ));
    }

    /**
     * @Route("/gestion-site/albums/{idPhoto}/delete-personne/{id}", name="deletePersonne")
     */
    public function deletePersonne($idPhoto,Personne $personne) {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($personne);
        $entityManager->flush();
        $this->get('session')->getFlashBag()->add('success',$personne->getNom() . ' ' . $personne->getPrenom() . ' enlevée');
        return $this->redirectToRoute('ajouterPersonne',array('id' => $idPhoto ));
    }

    /**
     * @Route("/gestion-site/delete-album/{id}", name="deleteAlbum")
     */
    public function deleteAlbum(Album $album) {
        $album = $this->getDoctrine()->getRepository(Album::class)->find($album->getId());
        if (count($album->getPhotos())){
            $this->get('session')->getFlashBag()->add('error','L\'album contient des photos et ne peut donc être supprimé');
        } else {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($album);
            $entityManager->flush();
            $this->get('session')->getFlashBag()->add('success','Album supprimé');
        }
        return $this->redirectToRoute('gestion-site-albums');
    }

    /**
     * @Route("/gestion-site/achats", name="gestion-site-achats")
     */
    public function achats() {
        $achats = $this->getDoctrine()
            ->getRepository(Achat::class)
            ->findBy(array(), array('date' => 'DESC'));
        return $this->render('gestion/achat.html.twig',array(

templates/gestion/achat.html.twig
{% extends 'gestion/nav.html.twig' %}

{% block body %}

    <div class="container content gestion">
        <h3 style="text-align: center">Achats</h3>
        <table>
            <thead>
                <tr>
                    <th>Identifiant</th>
                    <th>Date</th>
                    <th>Email client</th>
                    <th>Prix</th>
                </tr>
            </thead>

            <tbody>
                {% for achat in achats %}
                    <tr>
                        <td>{{ achat.id }}</td>
                        <td>{{ achat.date | date('d/m/Y')}}</td>
                        <td>{{ achat.client.email }}</td>
                        <td>{{ achat.prix }} €</td>
                    </tr>
                {% endfor %}
            </tbody>


        </table>

    </div>

{% endblock %}

templates/gestion/album.html.twig
{% extends 'gestion/nav.html.twig' %}

{% block body %}
    <div style="min-height:100vh" class="container content gestion">
        <h3 style="text-align: center">Mes albums</h3>

        {{ form_start(form) }}
        <div class="center-align row" style="margin-bottom: 5vh;">
            {{ form_widget(form.albumName) }}
            {{ form_widget(form.category) }}
            {{ form_widget(form.add) }}
        </div>
        {{ form_end(form) }}

        <table>
            <thead>
                <tr>
                    <th>Nom album</th>
                    <th>Date de création</th>
                    <th>Categorie</th>
                    <th>Mot de passe</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody>
                {% for album in albums %}
                    <tr>
                        <td>{{ album.albumName }}</td>
                        <td>{{ album.albumDate | date("d/m/Y") }}</td>
                        <td>
                            {% if album.category == 'free' %}
                                Gratuit
                            {% elseif album.category == 'payant' %}
                                Payant
                            {% elseif album.category == 'payant_protected' %}
                                Payant protégé
                            {% else %}
                                Gratuit protégé
                            {% endif %}
                        </td>
                        <td>{{ album.password is null ? 'Aucun mot de passe' : album.password }}</td>
                        <td>
                            <a href="{{ path('gererAlbum',{'albumId' : album.id}) }}" title="Gerer photos"><i class="small material-icons gray-text center-align" width="20px">build</i></a>
                            <a href="{{ path('deleteAlbum',{'id' : album.id}) }}" title="Supprimer l'album"><i class="small material-icons red-text center-align" width="20px">cancel</i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>


        </table>

    </div>

{% endblock %}

templates/gestion/carousel.html.twig
{% extends 'gestion/nav.html.twig' %}

{% block body %}
    <div style="min-height:100vh" class="container content gestion">
        <h3 style="text-align: center">Photos du carousel</h3>

        {{ form_errors(form) }}
        {{ form_start(form) }}
        <div class="center-align" style="margin-bottom: 5vh;">
            <div class="row">
                {{ form_widget(form.photo) }}
                <label style="margin-top: 30px" for="form_photo" class="col l2 m2 offset-m1 offset-l1 s12 button buttonBlue">Choisir photo</label>
                <span id="fileNamePhoto" style="margin-top: 35px" class="col l3 m3 s12 valign-wrapper">Aucun fichier séléctionné</span>
                {{ form_widget(form.add) }}
            </div>
        </div>
        {{ form_end(form) }}

        <table>
            <thead>
            <tr>
                <th>Photo</th>
                <th>Actions</th>
            </tr>
            </thead>

            <tbody>
            {% for carousel in carousels %}
                <tr>
                    <td><img src="{{ asset('uploads/carousel/' ~ carousel.photo) }}" width="50px" alt="photo"></td>
                    <td>
                        <a href="{{ path('deleteCarousel',{'id' : carousel.id}) }}" title="Supprimer la photo"><i class="small material-icons red-text center-align" width="20px">cancel</i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

{% endblock %}

templates/gestion/clients.html.twig
{% extends 'gestion/nav.html.twig' %}

{% block body %}

    <div class="container content gestion">
        <h3 style="text-align: center">Clients</h3>
        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Email</th>
                </tr>
            </thead>

            <tbody>
                {% for client in clients %}
                    <tr>
                        <td>{{ client.id }}</td>
                        <td>{{ client.email }}</td>
                    </tr>
                {% endfor %}
            </tbody>


        </table>

    </div>

{% endblock %}

templates/gestion/nav.html.twig
{% extends 'base.html.twig' %}

{% block navgerer %}
    <nav class=" nav-gerer">
        <div class="nav-content">
            <ul class="tabs tabs-transparent">
                {% set url_page = app.request.uri %}
                <li class="tab lienGerer"><a class="{{ 'album' in url_page ? 'activeTab' : '' }}" href="{{ path('gestion-site-albums') }}">MES ALBUMS</a></li>
                <li class="tab lienGerer"><a class="{{ 'prix' in url_page ? 'activeTab' : '' }}" href="{{ path('gestion-site-prix') }}">PRIX</a></li>
                <li class="tab lienGerer"><a class="{{ 'clients' in url_page ? 'activeTab' : '' }}" href="{{ path('gestion-site-clients') }}">CLIENTS</a></li>
                <li class="tab lienGerer"><a class="{{ 'achats' in url_page ? 'activeTab' : '' }}" href="{{ path('gestion-site-achats') }}">ACHATS</a></li>
                <li class="tab lienGerer"><a class="{{ 'presse' in url_page ? 'activeTab' : '' }}" href="{{ path('gestion-site-presse') }}">PRESSE</a></li>
                <li class="tab lienGerer"><a class="{{ 'carousel' in url_page ? 'activeTab' : '' }}" href="{{ path('gestion-site-carousel') }}">CAROUSEL</a></li>
                <li class="tab lienGerer"><a class="{{ 'profil' in url_page ? 'activeTab' : '' }}" href="{{ path('gestion-site-profil') }}">PROFIL</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% for flashMessage in app.session.flashbag.get('error') %}
            <div class="alert alert-danger">{{ flashMessage }}</div>
        {% endfor %}
        {% for flashMessage in app.session.flashbag.get('success') %}
            <div class="alert alert-success">{{ flashMessage }}</div>
        {% endfor %}
    </div>
{% endblock %}

{% block body %}
{% endblock %}

templates/gestion/personnes.html.twig
{% extends 'gestion/nav.html.twig' %}

{% block body %}

    <div class="retourGallerie">
        <a href="{{ path('gererAlbum',{'albumId' : photo.album.id}) }}" class="nextPreviousA">&lt; Retour photos</a>
    </div>

    <div class="container content gestion">
        <h3 style="text-align: center">Personnes sur la photo</h3>

        {{ form_start(form) }}
        <div class="center-align row" style="margin-bottom: 5vh;">
            {{ form_widget(form.nom) }}
            {{ form_widget(form.prenom) }}
            {{ form_widget(form.add) }}
        </div>
        {{ form_end(form) }}

        <table>
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody>
                {% for personne in personnes %}
                    <tr>
                        <td>{{ personne.nom }}</td>
                        <td>{{ personne.prenom }}</td>
                        <td>
                            <a href="{{ path('deletePersonne',{'id' : personne.id,'idPhoto' : photo.id}) }}" title="Supprimer la personne de la photo"><i class="small material-icons red-text center-align" width="20px">cancel</i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>


        </table>

    </div>

{% endblock %}

templates/gestion/photo.html.twig
{% extends 'gestion/nav.html.twig' %}

{% block body %}


    <div class="retourGallerie">
        <a href="{{ path('gestion-site-albums') }}" class="nextPreviousA">&lt; Retour albums</a>
    </div>

    <div class="container content gestion">
        <h3 style="text-align: center">{{ album.albumName }}</h3>

        {{ form_errors(form) }}
        {{ form_start(form) }}
        <div class="center-align" style="margin-bottom: 5vh;">
            <div class="row">
                {{ form_widget(form.photos) }}
                <label style="margin-top: 30px" for="form_photos" class="col l2 m2 s12 button buttonBlue">Choisir photo</label>
                <span id="fileNamePhoto" style="margin-top: 35px" class="col l6 m6 s12 valign-wrapper">Veuillez choisir une ou des photo(s)</span>
                {{ form_widget(form.add) }}
            </div>
        </div>
        {{ form_end(form) }}
        <table>
            <thead>
                <tr>
                    <th>Aperçu</th>
                    <th>Nom photo</th>
                    <th>Date de création</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody>
                {% for photo in album.photos %}
                    <tr>
                        <td><img src="{{ asset('uploads/photos/' ~ photo.photo) }}" width="50px" alt="photo"></td>
                        <td>{{ photo.photoName }}</td>
                        <td>{{ photo.photoDate | date("d/m/Y") }}</td>
                        <td>
                            <a href="{{ path('ajouterPersonne',{'id' : photo.id}) }}" title="Ajouter personnes"><i class="small material-icons gray-text center-align" width="20px">add</i></a>
                            <a href="{{ path('deletePhoto',{'albumId' : album.id,'photoId' : photo.id}) }}" title="Supprimer la photo"><i class="small material-icons red-text center-align" width="20px">cancel</i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>


        </table>

    </div>

{% endblock %}

templates/gestion/presse.html.twig
{% extends 'gestion/nav.html.twig' %}

{% block body %}
    <div style="min-height:100vh" class="container content gestion">
        <h3 style="text-align: center">Mes parutions dans la presse</h3>

        {{ form_errors(form) }}
        {{ form_start(form) }}
        <div class="center-align" style="margin-bottom: 5vh;">
            <div class="row">
                {{ form_widget(form.title) }}
                {{ form_widget(form.photo) }}
                <label style="margin-top: 30px" for="form_photo" class="col l2 m2 offset-m1 offset-l1 s12 button buttonBlue">Choisir photo</label>
                <span id="fileNamePhoto" style="margin-top: 35px" class="col l3 m3 s12 valign-wrapper">Aucun fichier séléctionné</span>
                {{ form_widget(form.add) }}
            </div>
        </div>
        {{ form_end(form) }}

        <table>
            <thead>
            <tr>
                <th>Source</th>
                <th>Photo</th>
                <th>Actions</th>
            </tr>
            </thead>

            <tbody>
            {% for presse in presses %}
                <tr>
                    <td>{{ presse.title }}</td>
                    <td><img src="{{ asset('uploads/presse/' ~ presse.photo) }}" width="50px" alt="photo"></td>
                    <td>
                        <a href="{{ path('deletePresse',{'id' : presse.id}) }}" title="Supprimer l'album"><i class="small material-icons red-text center-align" width="20px">cancel</i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

{% endblock %}

templates/gestion/prix.html.twig
{% extends 'gestion/nav.html.twig' %}

{% block body %}
    <div style="min-height:100vh" class="container content gestion">
        <h3 style="text-align: center">Tarifications</h3>

        {{ form_start(form) }}
        <div class="center-align" style="margin-bottom: 5vh;">
            <div class="row">
                {{ form_widget(form.categorie) }}
                {{ form_widget(form.ratioTaille) }}
                <span class="col s1 l1 m1" style="margin-top: 32px" id="infoRatio"></span>
                {{ form_widget(form.prix) }}
                {{ form_widget(form.add) }}
            </div>
        </div>
        {{ form_end(form) }}

        <table>
            <thead>
                <tr>
                    <th>Catégorie</th>
                    <th>Ratio de taille</th>
                    <th>Prix</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody>
                {% for format in formats %}
                    <tr>
                        <td>{{ format.categorie |capitalize }}</td>
                        <td>{{ format.ratioTaille }}</td>
                        <td>{{ format.prix }} €</td>
                        <td>
                            <a href="{{ path('deleteFormat',{'id' : format.id}) }}" title="Supprimer le format"><i class="small material-icons red-text center-align" width="20px">cancel</i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>


        </table>

    </div>

{% endblock %}

templates/gestion/profil.html.twig
{% extends 'gestion/nav.html.twig' %}

{% block body %}
    <div style="min-height:100vh" class="container content gestion">
        <h3 style="text-align: center">Mon profil</h3>

        {{ form_errors(form) }}
        {{ form_start(form) }}
        <div class="center-align" style="margin-bottom: 5vh;">
            <div class="row">
                {{ form_widget(form.password) }}
            </div>
            <div class="row">
                {{ form_widget(form.verification) }}
            </div>
            <div class="row">
                {{ form_widget(form.modifier) }}
            </div>
        </div>
        {{ form_end(form) }}
    </div>

{% endblock %}