src/Entity/Album.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AlbumRepository")
 */
class Album
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $album_name;

    /**
     * @ORM\Column(type="date")
     */
    private $album_date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Photo", mappedBy="photo_album")
     */
    private $album_photos;

    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $password;

    /**
     * @ORM\Column(type="string")
     */
    private $category;

    public function __construct()
    {
        $this->album_photos = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param mixed $password
     */
    public function setPassword($password)
    {
        $this->password = $password;
    }

    /**
     * @return mixed
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param mixed $category
     */
    public function setCategory($category)
    {
        $this->category = $category;
    }




    public function getPhotos()
    {
        return $this->album_photos;
    }

    public function addPhoto(?Photo $photo): void
    {
        $photo->setPost($this);
        if (!$this->album_photos->contains($photo)) {
            $this->album_photos->add($photo);
        }
    }
    public function removePhoto(Photo $photo): void
    {
        $photo->setPost(null);
        $this->album_photos->removeElement($photo);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAlbumName(): ?string
    {
        return $this->album_name;
    }

    public function setAlbumName(string $album_name): self
    {
        $this->album_name = $album_name;

        return $this;
    }

    public function getAlbumDate(): ?\DateTimeInterface
    {
        return $this->album_date;
    }

    public function setAlbumDate(\DateTimeInterface $album_date): self
    {
        $this->album_date = $album_date;

        return $this;
    }
}

src/Controller/Payment/PaymentController.php
<?php

namespace App\Controller\Payment;

use App\Entity\Achat;
use App\Entity\Client;
use App\Entity\Format;
use App\Entity\Photo;
use DateTime;
use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\Payer;
use PayPal\Api\Payment;
use PayPal\Api\PaymentExecution;
use PayPal\Api\RedirectUrls;
use PayPal\Api\Transaction;
use PayPal\Auth\OAuthTokenCredential;
use PayPal\Exception\PayPalConnectionException;
use PayPal\Rest\ApiContext;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class PaymentController extends Controller
{

    public function getPanierFromSession() {
        $panierSession = $this->get('session')->get('panier');
        $repositoryPhoto =  $this->getDoctrine()->getRepository(Photo::class);
        $repositoryFormat =  $this->getDoctrine()->getRepository(Format::class);
        $panier = array();
        if ($panierSession !== null) {
            foreach ($panierSession as $photoId => $formats) {
                $photo = $repositoryPhoto->find($photoId);
                list($width,$height) = getimagesize($this->getParameter('photos_directory') . DIRECTORY_SEPARATOR . $photo->getPhoto());
                foreach ($formats as $format) {
                    $format = $repositoryFormat->find($format);
                    $panier[] = array(
                        "photo" => $photo,
                        "format" => $format,
                        "width" => (int) ($format->getRatioTaille() * $width),
                        "height" => (int) ($format->getRatioTaille() * $height)
                    );
                }
            }
        }
        return $panier;
    }

    /**
     * @Route("/panier", name="panier")
     */
    public function panier()
    {
        $panier = $this->getPanierFromSession();
        return $this->render('payment/panier.html.twig', [
            'controller_name' => 'PaymentController',
            'panier'=> $panier
        ]);
    }

    public function viderPanier() {
        $session = $this->get('session');
        if ($session == null ) {
            $session->start();
        }
        $session->set('panier', null);
    }

    /**
     * @Route("/photos/abandonner-panier", name="abandonnerPanier")
     */
    public function abandonnerPanier() {
        $this->viderPanier();
        return $this->redirectToRoute('accueil');
    }

    /**
     * @Route("/acheter/email", name="email")
     */
    public function email(Request $request) {
        $client = new Client();

        $form = $this->createFormBuilder($client)
            ->add('email', TextType::class, array("label" => false,'attr' => array('class' => 'emailInput browser-default','placeholder' => 'Email')))
            ->add('save', SubmitType::class, array('label' => 'Continuer achat','attr' => array('class' => 'noInputStyle button buttonGreen center-align')))
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $client = $form->getData();
            $clientSearched = $this->getDoctrine()->getRepository(Client::class)->findBy(array(
                'email' => $client->getEmail()
            ));
            if (count($clientSearched)  == 0) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($client);
                $entityManager->flush();
            } else {
                $client = $clientSearched[0];
            }
            $this->get('session')->set("clientId",$client->getId());

            return $this->redirectToRoute('acheter');
        }

        return $this->render('payment/email.html.twig', [
            'controller_name' => 'PaymentController',
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/achat", name="achat")
     */
    public function achat(\Swift_Mailer $mailer) {
        $apiContext = new ApiContext(
            new OAuthTokenCredential(
                $this->getParameter('paypal_api_key'),
                $this->getParameter('paypal_secret')
            )
        );
        $apiContext->setConfig(
            array(
                'mode' => 'live'
              )
        );
        if (!(isset($_GET["paymentId"]) && isset($_GET["PayerID"]))) {
            throw new \Exception('Quelque chose s\' est mal passé !');
        }
        $payment = Payment::get($_GET["paymentId"],$apiContext);
        $transactions = $payment->getTransactions();
        $execution = (new PaymentExecution())
            ->setPayerId($_GET["PayerID"])
            ->setTransactions($transactions);
        $paymentValidated = false;
        $links = array();
        try {
            $paymentUniqueId = $this->get("session")->get("paymentUniqueId");
            if ($paymentUniqueId == $transactions[0]->getCustom()){
                $payment->execute($execution,$apiContext);
                $paymentValidated = true;
                $panier = $this->getPanierFromSession();
                //Resize the photo
                foreach ($panier as $photo) {
                    $filePathFullPhoto = $this->getParameter("photos_directory")
                        . DIRECTORY_SEPARATOR
                        . $photo["photo"]->getPhoto();
                    $ext = pathinfo($filePathFullPhoto, PATHINFO_EXTENSION);
                    $fileName = hash("sha256",$photo["photo"]->getPhoto() . $photo["format"]->getId()) . '.' . $ext ;;
                    $filePath = $this->getParameter("photos_directory")
                        . DIRECTORY_SEPARATOR
                        . $fileName;
                    list($width,$height) = getimagesize($filePathFullPhoto);
                    if (!file_exists($filePath)) {
                        $src = imagecreatefromjpeg($filePathFullPhoto);
                        $dst = imagecreatetruecolor($photo["width"], $photo["height"]);
                        imagecopyresampled($dst, $src, 0, 0, 0, 0, $photo["width"], $photo["height"], $width, $height);
                        imagejpeg ( $dst,  $filePath );
                    }
                    $links[] = $fileName;
                }
                $clientId = $this->get('session')->get("clientId");
                $client = $this->getDoctrine()->getRepository(Client::class)->find($clientId);
                $message = (new \Swift_Message('Achat de photos'))
                    ->setFrom('photosportnormandy@gmail.com')
                    ->setTo($client->getEmail())
                    ->setBody(
                        $this->renderView(
                            'emails/payment_done.html.twig',
                            array('links' => $links)
                        ),
                        'text/html'
                    )
                ;
                $mailer->send($message);
                $achat = new Achat();
                $achat->setClient($client);
                $achat->setDate(new DateTime());
                $achat->setPrix($this->get('session')->get('prix'));
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($achat);
                $entityManager->flush();
                $this->viderPanier();
                $this->get('session')->getFlashBag()->add('success','Paiement effectué avec succès, photos envoyées à l\'addresse ' . $client->getEmail());
            } else {
                $this->get('session')->getFlashBag()->add('error','Erreur lors du paiement, paiement non effectué');
            }
        } catch (PayPalConnectionException $e) {
//            var_dump(json_decode($e->getData()));
            throw new \Exception('Erreur lors du paiement');
        }

        return $this->render('payment/acheter.html.twig', [
            'controller_name' => 'PaymentController',
            'links' => $links,
            'isPaymentValidated' => $paymentValidated
        ]);
    }

    /**
     * @Route("/acheter", name="acheter")
     */
    public function buy() {
        $apiContext = new ApiContext(
            new OAuthTokenCredential(
                $this->getParameter('paypal_api_key'),
                $this->getParameter('paypal_secret')
            )
        );
        $apiContext->setConfig(
            array(
                'mode' => 'live'
            )
        );
        $payment = new Payment();
        $payment->setIntent("sale");
        $redirectUrls = new RedirectUrls();
        $redirectUrls->setReturnUrl($this->generateUrl('achat',array(),UrlGeneratorInterface::ABSOLUTE_URL) );
        $redirectUrls->setCancelUrl($this->generateUrl('panier',array(),UrlGeneratorInterface::ABSOLUTE_URL));
        $payment->setRedirectUrls($redirectUrls);
        $payment->setPayer(
            (new Payer())->setPaymentMethod('paypal')
        );

        $list = new ItemList();
        $panier = $this->getPanierFromSession();
        $prixTotal = 0;
        foreach ($panier as $product) {
            $item = (new Item())
                ->setName($product["photo"]->getPhotoName() . ' ' . $product["width"] . 'x' . $product["height"])
                ->setCurrency("EUR")
                ->setPrice($product["format"]->getPrix())
                ->setQuantity(1);
            $prixTotal += $product["format"]->getPrix();
            $list->addItem($item);
        }

        $details = (new Details())
            ->setSubtotal($prixTotal);

        $amout = (new Amount())
            ->setTotal($prixTotal)
            ->setDetails($details)
            ->setCurrency("EUR");

        $uniqueId = md5(uniqid());
        $this->get("session")->set("paymentUniqueId",$uniqueId);

templates/payment/acheter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon panier{% endblock %}


{% block body %}
    <div class="content">
        <div class="container">
            {% for flashMessage in app.session.flashbag.get('error') %}
                <div class="alert alert-danger">{{ flashMessage }}</div>
            {% endfor %}
            {% for flashMessage in app.session.flashbag.get('success') %}
                <div class="alert alert-success">{{ flashMessage }}</div>
            {% endfor %}
        </div>
        <div class="container">
            {% if isPaymentValidated %}
                <h4  style="margin-bottom: 5vh" class="center-align">Liens pour telecharger les photos</h4>
                <ul>
                    {% for link in links %}
                        {% set url = absolute_url('uploads/photos/' ~ link) %}
                        <ul><a href="{{  url }}" download>{{ url }}</a></ul>
                    {% endfor %}
                </ul>
            {% else %}
                <div>
                    Paiement non validé
                </div>
            {% endif %}
            <div style="text-align: center;margin-top: 5vh">
                <a class="button buttonGreen center-align" href="{{ path('accueil') }}">Retour accueil</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/payment/email.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon panier{% endblock %}

{% block body %}
    <h5 style="font-family: Lato-Bold;text-align: center">Entrez votre email pour recevoir les photos</h5>
    <div style="text-align: center">
        {{ form_start(form) }}
        {{ form_widget(form ) }}
        {{ form_end(form) }}
    </div>

{% endblock %}

templates/payment/panier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon panier{% endblock %}

{% block body %}
    <div class="container content" style="min-height: 80vh">

        {% if panier | length > 0 %}
            <h4 class="center-align" style="font-family: Lato-Bold" >VOTRE PANIER</h4>

            <div class="containerTableau">
                <table class="tableauPanier">

                    <thead>
                        <tr>
                            <th>Miniature</th>
                            <th>Album</th>
                            <th>Dimensions</th>
                            <th>Prix</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% set total = 0 %}
                        {% for row in panier %}
                            <tr>
                                <td><img src="{{ asset('uploads/watermarked/' ~ row.photo.watermark) }}" width="80px" alt=""></td>
                                <td>{{ row.photo.album.albumName }}</td>
                                <td>{{ row.width }} x {{ row.height }}</td>
                                <td>{{ row.format.prix }} €</td>
                                {% set total = total + row.format.prix %}
                            </tr>
                        {% endfor %}

                    </tbody>
                    <tfoot>
                        <tr class="noStyle">
                            <td class="noStyle"></td>
                            <td class="noStyle"></td>
                            <td>Total</td>
                            <td>{{ total }} €</td>
                        </tr>
                    </tfoot>

                </table>
            </div>

            <div class="containerButtons buttonsPanier">
                <a class="button buttonRed center-align" href="{{ path('abandonnerPanier') }}">Abandonner</a>
                <a class="button buttonGreen center-align" href="{{ path('email') }}">Acheter</a>
            </div>
        {% else %}
            <h5 class="center-align" style="font-family: Lato-Bold;margin-top: 10vh;" >Panier vide</h5>
        {% endif %}
        </div>
{% endblock %}